### ISSUE TITLE
"Mangement" typo 

### ISSUE THREAD

**Issue by daamsie** [ortus-docs/cfconfig-docs#12]
There are a couple of typos in here. This is not really a docs bug as the same problem exists in the code. It seems I can't report issues in that project though, so reporting it here.

```
// True/false
name='applicationMangement' type='boolean'
// True/false
name='sessionMangement' type='boolean'
```

**Comment by bdw429s** [comment]
Thanks @daamsie I'll need to rename these in the code and put in a stop gap to look for both names for a while so old JSON files work.  The ticket tracker for CFConfig is here: 

https://ortussolutions.atlassian.net/browse/CFCONFIG

**Comment by bdw429s** [comment]
https://ortussolutions.atlassian.net/browse/CFCONFIG-40

**Comment by bdw429s** [comment]
@daamsie This is fixed in the latest patch release

**sessionMangement** was already fixed in the code but the docs needed updated.

**applicationMangement** needed fixed in both places
